### PR TITLE
add explicit example to to-many relations

### PR DESCRIPTION
**Pull request by G3z**
it took me a good hour to notice the final . in the name

### CODE REVIEW

**Comment by tabuna** [comment]
Sorry for this hour. Why didn’t you ask about it in the chat?

We can also indicate in more detail why this point is needed. 
We are doing an example with this below, but let's add an extra tip.

**Comment by tabuna** [comment]
Hmm, we can completely save the user from thinking about specifying this point:

```php
    /**
     * @return self
     */
    public function multiple(): self
    {
        $this->attributes['multiple'] = 'multiple';
        $this->attributes['name'] = Str::finish($this->get('name'), '.');

        return $this;
    }
```

**Comment by G3z** [comment]
Sorry, I didn't mean to brag!
I like that even more!
While looking at that part of code I was wondering if you had a use case in witch that could cause you troubles

**Comment by tabuna** [comment]
Something like this might look like this:
https://github.com/orchidsoftware/platform/tree/multiple_auto_dot
Could put this method into trait

**Comment by tabuna** [comment]
_For the story_

I worked through this issue and came to the conclusion that we [cannot do this.](https://github.com/orchidsoftware/platform/pull/1077) 
Due to the fact that the form and the builder of forms are different independent objects.
I'm sorry :disappointed:, but I can’t do it otherwise we package will suffer greatly.

**Pull request merged**
